#version: '3.11'

services:
  redis:
    image: pkounelis/persadomlops/redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  fastapi-app:
    image: pkounelis/persadomlops/fastapi-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - app-network

  locust:
    image: pkounelis/persadomlops/locust:latest
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    depends_on:
      - fastapi-app
    networks:
      - app-network

  prometheus:
    image: pkounelis/persadomlops/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: pkounelis/persadomlops/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
